# Build ASP.NET Core project using VSTS
# https://docs.microsoft.com/vsts/pipelines/languages/dotnet-core?view=vsts

queue: 'Hosted Linux Preview'

steps:
- powershell: . build.ps1 
  displayName: PowerShell Cake Script