# Build ASP.NET Core project using VSTS
# https://docs.microsoft.com/vsts/pipelines/languages/dotnet-core?view=vsts

queue: 'Hosted'

- task: DotNetCoreInstaller@0
  inputs:
    version: '2.1.400'

steps:
- powershell: .\build.ps1 
  displayName: PowerShell Cake Script