# Build ASP.NET Core project using VSTS
# https://docs.microsoft.com/vsts/pipelines/languages/dotnet-core?view=vsts

queue: 'Hosted Linux Preview'

steps:
- task: DotNetCoreInstaller@0
  displayName: Use .NET Core sdk 2.1.401
  inputs:
    version: 2.1.401

- bash: . build.sh
  displayName: Bash Cake Script

# - task: DockerCompose@0
#   displayName: 'Run a Docker Compose command'
#   inputs:
#     containerregistrytype: 'Container Registry'

#     dockerRegistryEndpoint: meliehl

#     dockerComposeCommand: 'up -d crawler-sqlserver'

# - bash: . build.sh -target=Integration-Test
#   displayName: Bash Cake Integration-Test Script
#   env:
#     ConnectionStrings:default: Data Source=0.0.0.0;Initial Catalog=MorningBrew;Persist Security Info=True;User ID=sa;Password=Crawler_Brew

- bash: . build.sh -target=Publish-Test
  displayName: Bash Cake Publish-Test Script

- task: PublishTestResults@2
  displayName: Publish Test Results
  inputs:
    testRunner: VSTest
    testResultsFiles: '*.trx'
    searchFolder: '$(build.SourcesDirectory)/tests/Artifacts'
  continueOnError: true
  condition: succeededOrFailed()
  
- task: PublishCodeCoverageResults@1
  displayName: Publish code coverage from coverage.cobertura.xml
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(build.SourcesDirectory)/tests/Artifacts/**/coverage.cobertura.xml'
    reportDirectory: '$(build.SourcesDirectory)/tests/Artifacts/Report'