# Build ASP.NET Core project using VSTS
# https://docs.microsoft.com/vsts/pipelines/languages/dotnet-core?view=vsts

queue: 'Hosted'
variables:
  buildConfiguration: 'Release'

steps:
- task: cake-build.cake.cake-build-task.Cake@0
  displayName: Cake