# Build ASP.NET Core project using VSTS
# https://docs.microsoft.com/vsts/pipelines/languages/dotnet-core?view=vsts

queue: 'Hosted Linux Preview'

steps:
- task: DotNetCoreInstaller@0
  displayName: Use .NET Core sdk 2.1.402
  inputs:
    version: 2.1.402

- bash: . build.sh -target=BuildAndUnitTest
  displayName: Bash Cake Script

- bash: |
   docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=Crawler_Brew' \
      -p 1433:1433 \
      -d microsoft/mssql-server-linux:2017-latest 
  displayName: 'Start SqlServer'

- bash: .\build.sh -target=MigrationAndIntegrationTest
  displayName: Bash Cake Integration-Test Script
  env:
    ConnectionStrings:default: Data Source=localhost;Initial Catalog=MorningBrew;Persist Security Info=True;User ID=sa;Password=Crawler_Brew

- bash: . build.sh -target=Publish-Test
  displayName: Bash Cake Publish-Test Script

- task: PublishTestResults@2
  displayName: Publish Test Results
  inputs:
    testRunner: VSTest
    testResultsFiles: '*.trx'
    searchFolder: '$(build.SourcesDirectory)/tests/Artifacts'
  continueOnError: true
  condition: succeededOrFailed()
  
- task: PublishCodeCoverageResults@1
  displayName: Publish code coverage from coverage.cobertura.xml
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(build.SourcesDirectory)/tests/Artifacts/coverage.cobertura.xml'
    reportDirectory: '$(build.SourcesDirectory)/tests/Artifacts/Report'