# Build ASP.NET Core project using VSTS
# https://docs.microsoft.com/vsts/pipelines/languages/dotnet-core?view=vsts

queue: 'Hosted VS2017'

steps:
- task: DotNetCoreInstaller@0
  displayName: Use .NET Core sdk 2.2.101
  inputs:
    version: 2.2.101

- powershell: .\build.ps1 -Target=BuildAndUnitTest
  displayName: PowerShell Cake Script

- powershell: 'sqllocaldb start mssqllocaldb.'
  displayName: 'PowerShell Start LocalDB Script'

- powershell: .\build.ps1 -target=MigrationAndIntegrationTest
  displayName: PowerShell Cake Integration-Test Script
  env:
    ConnectionStrings:default: Data Source=(LocalDb)\mssqllocaldb;Initial Catalog=MorningBrew;Integrated Security=SSPI

- powershell: .\build.ps1 -target=Publish-Test
  displayName: PowerShell Cake Publish-Test Script

- task: PublishTestResults@2
  displayName: Publish Test Results
  inputs:
    testRunner: VSTest
    testResultsFiles: '*.trx'
    searchFolder: '$(build.SourcesDirectory)/tests/Artifacts'
  continueOnError: true
  condition: succeededOrFailed()

- task: PublishCodeCoverageResults@1
  displayName: Publish code coverage from coverage.cobertura.xml
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(build.SourcesDirectory)/tests/Artifacts/coverage.cobertura.xml'
    reportDirectory: '$(build.SourcesDirectory)/tests/Artifacts/Report'
