# Build ASP.NET Core project using VSTS
# https://docs.microsoft.com/vsts/pipelines/languages/dotnet-core?view=vsts

queue: 'Hosted Ubuntu 1604'

steps:
- task: DotNetCoreInstaller@0
  displayName: Use .NET Core sdk 2.2.203
  inputs:
    version: 2.2.103

- bash: . build.sh -target=BuildAndUnitTest
  displayName: Bash Cake Script

- task: Docker@1
  displayName: 'Run sql server image'
  inputs:
    containerregistrytype: 'Container Registry'
    command: 'Run an image'
    imageName: 'mcr.microsoft.com/mssql/server'
    containerName: sqlserver
    ports: '1433:1433'
    envVars: |
     ACCEPT_EULA=Y
     SA_PASSWORD=Crawler_Brew
    restartPolicy: always

- bash: |
   IP=`docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' sqlserver`
   echo "##vso[task.setvariable variable=SqlServer:Host;]$IP"
  displayName: 'Get docker sqlserver Ip'

- bash: . build.sh -target=MigrationAndIntegrationTest
  displayName: Bash Cake Integration-Test Script
  env:
    ConnectionStrings:default: Data Source=$(SqlServer:Host);Initial Catalog=MorningBrew;Persist Security Info=True;User ID=sa;Password=Crawler_Brew

- bash: . build.sh -target=Publish-Test
  displayName: Bash Cake Publish-Test Script

- task: PublishTestResults@2
  displayName: Publish Test Results
  inputs:
    testRunner: VSTest
    testResultsFiles: '*.trx'
    searchFolder: '$(build.SourcesDirectory)/tests/Artifacts'
  continueOnError: true
  condition: succeededOrFailed()

- task: PublishCodeCoverageResults@1
  displayName: Publish code coverage from coverage.cobertura.xml
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(build.SourcesDirectory)/tests/Artifacts/coverage.cobertura.xml'
    reportDirectory: '$(build.SourcesDirectory)/tests/Artifacts/Report'
