version: '3.5'

services:
  crawler-sqlserver:
    image: mcr.microsoft.com/mssql/server 
    hostname: crawler-sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Crawler_Brew"
      ACCEPT_EULA: "Y"
    networks:
      crawler-nw:
  sqlserver-migration-dbup:
    depends_on:
      - crawler-sqlserver
    build:
      context: .
      dockerfile: ./src/SqlServer.Migration.DbUp/Dockerfile
    environment:
      - ConnectionStrings:default=Data Source=crawler-sqlserver;Initial Catalog=MorningBrew;Persist Security Info=True;User ID=sa;Password=Crawler_Brew
    networks:
      crawler-nw:
  sqlserver-migration-fluent:
    depends_on:
      - crawler-sqlserver
    build:
      context: .
      dockerfile: ./src/SqlServer.Migration.Fluent/Dockerfile
    environment:
      - ConnectionStrings:default=Data Source=crawler-sqlserver;Initial Catalog=MorningBrew;Persist Security Info=True;User ID=sa;Password=Crawler_Brew
    networks:
      crawler-nw:
  crawler-runner:
    depends_on:
      - crawler-sqlserver
    build:
      context: .
      dockerfile: ./src/Runner/Dockerfile
    environment:
      - ConnectionStrings:default=Data Source=crawler-sqlserver;Initial Catalog=MorningBrew;Persist Security Info=True;User ID=sa;Password=Crawler_Brew
    networks:
      crawler-nw:    
  crawler-hangfire:
    depends_on:
      - crawler-sqlserver
    build:
      context: .
      dockerfile: ./src/Hangfire.Runner/Dockerfile
    ports:
      - 5000:80
    environment:
      - ConnectionStrings:default=Data Source=crawler-sqlserver;Initial Catalog=MorningBrew;Persist Security Info=True;User ID=sa;Password=Crawler_Brew
      - ConnectionStrings:hangfire=Data Source=crawler-sqlserver;Initial Catalog=Hangfire;Persist Security Info=True;User ID=sa;Password=Crawler_Brew
    networks:
      crawler-nw:    
networks:
  crawler-nw:
    name: crawler-nw